/*
Problem 2
Each new term in the Fibonacci sequence is generated by adding the 
previous two terms. By starting with  1 and 2 the firt ten terms will be:
1,2,3,5,8,13,21,34,55,89,....
By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.
*/

#include <iostream>
using namespace std;

int sumOfEvenFibonacci(int limit) {
    int a = 1, b = 2, sum = 0;
    
    while (b < limit) {
        if (b % 2 == 0) {
            sum += b;
        }
        int next = a + b;
        a = b;
        b = next;
    }
    return sum;
}

int main() {
    const int limit = 4000000;
    int result = sumOfEvenFibonacci(limit);
cout << "The sum of the even-valued Fibonacci terms not exceeding " << limit << " is: " << result << endl;
    return 0;
}